### ISSUE TITLE
Support for feast 0.31

### ISSUE THREAD

**Issue by mmarqz** [yummyml/yummy#32]
Currently the feast plugin requires feast 0.22.4, will there be a new release that supports the latest version 0.31?

**Comment by qooba** [comment]
Yummy project will go in rust direction thus latest feast versions probably won't be supported.

**Comment by mmarqz** [comment]
will there still be a feature store component in yummy? or only feature server?

**Comment by qooba** [comment]
Hi, @mmarqz  I have added support for `feast~=0.34.1` . But please be aware that not all `feast` features are currently supported.
