### ISSUE TITLE
How active is this maintained?

### ISSUE THREAD

**Issue by ion-elgreco** [yummyml/yummy#34]
I first want to say a very nice extension you have made for `feast` to allow Polars backend and delta as a source, also nice work on the mlflow server.

I'm going to try it out because we mainly use Polars for processing and delta as our storage. 

However I would like to know how actively you are still working on it, and if you're open  to others contributing?

**Comment by qooba** [comment]
Thank you @ion-elgreco! I'm glad to hear that you find the extension useful for integrating feast with Polars and delta.

Currently, my focus has shifted slightly towards another project, yummy-rs. Nevertheless, I am definitely open to contributions and would appreciate any input or help to continue improving the feast extension. Feel free to open issues, suggest enhancements, or submit PRs.

Looking forward to seeing your contributions and I hope the extension serves your needs well!
